### ISSUE TITLE
Missing ExifTag for time zone

### ISSUE THREAD

**Issue by StefanOltmann** [dragon66/pixymeta#10]
To properly convert ExifTag.DATE_TIME_ORIGINAL to milliseconds we need to read the time zone flag (see 0x9011 on https://exiftool.org/TagNames/EXIF.html). This seems to be missing.

**Comment by dragon66** [comment]
@StefanOltmann Added 3 more enums for your purpose and a few other tags.
        OFFSET_TIME("Offset Time", (short)0x9010),
	OFFSET_TIME_ORIGINAL("Offset Time Original", (short)0x9011),
	OFFSET_TIME_DIGITIZED("Offset Time Digitized", (short)0x9012),

**Comment by StefanOltmann** [comment]
Thank you, that helps me to retrieve the correct date.

For anyone interested in how it’s done, look at https://github.com/drewnoakes/metadata-extractor/blob/5773aa0e2877d5bafb091c6cbccb550ad2a58479/Source/com/drew/metadata/Directory.java#L862 .
