### ISSUE TITLE
File grows twice when adding a comment

### ISSUE THREAD

**Issue by ike600** [dragon66/pixymeta#14]
I'm trying to add a comment to a TIFF file. The comment is added perfectly, however image files are always growing in size twice, e.g. was 5.4M, after adding a comment 10.8Mb.

```
public class TryPixyMeta {
    public static void main(String args[]) throws IOException {
        try(InputStream is = new FileInputStream("image.tif");
            OutputStream os = new FileOutputStream("image-commented.tif")) {
            RandomAccessInputStream rais = new FileCacheRandomAccessInputStream(is);
            RandomAccessOutputStream raos = new FileCacheRandomAccessOutputStream(os);
            List<String> comments = Arrays.asList("Hello world!");
            TIFFMeta.insertComments(comments, rais, raos);
        }
    }
}

```
What am I doing wrong?

An example of image is attached.

[image.zip](https://github.com/user-attachments/files/16420539/image.zip)

**Comment by dragon66** [comment]
Interesting finding. I don't remember for sure but got the feeling I heard similar claim before for other metadata operations related to TIFF. Need to debug and see what could be the issue.

**Comment by dragon66** [comment]
It turns out to be a big bug! I set the wrong write offset accidently to roughly the end of the original image size so it basically doubles the file size - first half of the image becomes garbage! The only right one seems to be the insert Exif part. Fixed it. Thanks a lot for pointing it out.

Happy coding!

**Comment by ike600** [comment]
Thank you so much for the prompt fix and for this nice library!
