### ISSUE TITLE
not working with current "com.github.jai-imageio:jai-imageio-core:1.3.1"

### ISSUE THREAD

**Issue by k3b** [dragon66/pixymeta#3]
the lib works perfect on win7-64 with the demo using

```
  > java  -Dfile.encoding=UTF-8 -classpath pixymeta.jar;slf4j-api-1.7.12.jar;slf4j-log4j12-1.7.12.jar;jai_imageio.jar;log4j-1.2.17.jar pixy.test.TestPixyMeta ./images/cmykjpg.jpg
```

if you copy the images to `pixymeta\lib\images folder

However if i replace the provided `jai_imageio.jar` with the current `jai_imageio-core-1.3.1.jar`

i get

> java.lang.NullPointerException
>   at pixy.util.MetadataUtils.createThumbnail(Unknown Source)
>   at pixy.test.TestPixyMeta.createThumbnail(Unknown Source)
>   at pixy.test.TestPixyMeta.main(Unknown Source)

when calling

> ```
>   fin = new FileInputStream("images/f1.tif");
>   fout = new FileOutputStream("f1-irbthumbnail-inserted.tif");
> 
>   Metadata.insertIRBThumbnail(fin, fout, createThumbnail("images/f1.tif"));
> ```

I assume that `jai_imageio.jar` corresponds to 
'com.sun.media:jai_imageio:1.1' which is not available any more due to jpeg200-copyright problems

Do you know any free imageio lib that let all tests pass?

I also tried to use com.twelvemonkeys.imageio:imageio-tiff:3.2.1 and got

> java.lang.NegativeArraySizeException
>   at pixy.meta.png.PNGMeta.readChunks(PNGMeta.java:192)
>   at pixy.meta.png.PNGMeta.insertChunks(PNGMeta.java:74)
>   at pixy.meta.png.PNGMeta.insertComments(PNGMeta.java:99)
>   at pixy.meta.Metadata.insertComments(Metadata.java:134)

when calling

```
        fin = new FileInputStream("images/butterfly.png");
        fout = new FileOutputStream("comment-inserted.png");

        Metadata.insertComments(fin, fout, Arrays.asList("Comment1", "Comment2"));

```

**Comment by k3b** [comment]
to reproduce i used these 
from https://github.com/k3b/pixymeta

successfull using jai_imageio.jar

```
  ant demo
```

failed using jai_imageio-core-1.3.1.jar

```
   ant ttest
```

I found this issue when working on https://github.com/k3b/pixymeta-android (branch gradle-build) and realized that the issue depends on the included lib

**Comment by dragon66** [comment]
@k3b I tried to replace jai_imageio.jar with jai_imageio-core-1.3.1.jar or some other version before but with no success. I believe jai_imageio-core doesn't contain all the classes needed for image IO function. The only reason jai_imageio.jar is there is to read TIFF images. Then pixymeta can create thumbnail images from them. 

For the desktop version, I was planning to replace it with my own TIFF reader but my TIFF reader is not working for all types of TIFF compression yet.

I haven't found other open source decent easy to use TIFF reader yet. If jpeg2000 copyright is the only problem with the included library, can you just remove that part as pixymeta doesn't use it at all.

**Comment by k3b** [comment]
the failed tiff test works with the "com.twelvemonkeys.imageio:imageio-tiff:3.2.1" lib but then adding comments to png fails. `jai_imageio.jar` uses native-c-libPng so it is not suitable for my goal to have a set of jars with one codebase for android and non-pixymeta in https://github.com/k3b/pixymeta-android. one codebase is possible but i donot like jars with cpu-specific content.

Would it be ok for you to 
- to merge dragon66/pixymeta with dragon66/pixymeta-android to one codebase and
- move from ant build to gradle build and
- remove the intermediate classes from git repository?

If yes i will replace mavens jai_imageio-core-1.3.1.jar back to local copy of jai_imageio.jar lib so the test should pass.

If you donot have experience with gradle try 
- download my pixymeta-android branch
- call `gradlew --gui` and
- select "pixymeta-j2se-demo/fatJar" 

this will generate a standalone pixymeta-android\pixymeta-j2se-demo\build\libs\pixymeta-j2se-demo-all.jar that conains all dependent jars of portable-pixymeta linked against j2se-runtime and including the test images.

calling `java -jar pixymeta-j2se-demo-all.jar` will run the test

[Update] 

i modified jai_imageio and removed the jj2000 stuff (except jj2000\j2k\util\MsgLogger.class) and the manifest-folder and get

```
[main] ERROR pixy.demo.j2se.TestPixyMetaJ2se - cannot set comment to images/butterfly.png
java.lang.NegativeArraySizeException
    at pixy.meta.png.PNGMeta.readChunks(PNGMeta.java:192)
    at pixy.meta.png.PNGMeta.insertChunks(PNGMeta.java:74)
    at pixy.meta.png.PNGMeta.insertComments(PNGMeta.java:99)
    at pixy.meta.Metadata.insertComments(Metadata.java:134)
    at pixy.demo.j2se.TestPixyMetaJ2se.main(TestPixyMetaJ2se.java:172)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

the same error as when using com.twelvemonkeys.imageio:imageio-tiff:3.2.1 
can you analyse the png problem. if so we can use com.twelvemonkeys.imageio:imageio-tiff:3.2.1

**Comment by dragon66** [comment]
@k3b I haven't really debugged the PNG issue but I guess it comes from the fact you put the image inside a jar file. I have found when reading image from a jar file, the read() method of Java IO doesn't return the expected bytes. 

You can try the following to see if the error is still there: on line 193 of PNGMeta, replace IOUtils.read(is, buf, 0, data_len) with IOUtils.readFully(is, buf,0, data_len). Basically every IOUtils.read(is, buf) or similar methods should be forced to use readFully(is, buf) instead. There are still some cases where I failed to do that and they are all related to PNG.

I also did a new search-and-replace and hopefully every thing has been covered.

**Comment by k3b** [comment]
BINGO

i have replaced both read with readFully in  PNGMeta and now the test succeeds using com.twelvemonkeys.imageio:imageio-tiff:3.2.1.

I found no other occurences of IOUtils.read(is, ...) in the android branch only  IOUtils.read(is)

**Comment by dragon66** [comment]
Great!
