### ISSUE TITLE
error running first program TestPixyMeta 

### ISSUE THREAD

**Issue by ttulinskySoCal** [dragon66/pixymeta#6]
I just cloned the repo (git clone https://github.com/dragon66/pixymeta.git) 
Opened it in Eclipse Proton 
Tried to Run TestPixyMeta.java
I get the error 
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at pixy.test.TestPixyMeta.test(TestPixyMeta.java:51)
```
Line 51 is:
	`	Map<MetadataType, Metadata> metadataMap = Metadata.readMetadata(args[0]);`
	
Looks like it is expecting argments and found none. 
None are defined in Run Configurations. 
What are appropriate arguments?

**Comment by ttulinskySoCal** [comment]
Never mind.
I figured out that the argument should be an image file with metadata. 
It would be good to print a "usage" message, and/or document how to run it.

**Comment by dragon66** [comment]
@ttulinskySoCal thanks for your suggestion.
