### ISSUE TITLE
How to read image width and height of the JPEG part?

### ISSUE THREAD

**Issue by StefanOltmann** [dragon66/pixymeta#8]
I want to obtain the image width and length from the JPEG directory, but `pixy.meta.jpeg.JFIF` has no field for that and also no method to get it.

I currently use [metadata-extractor](https://github.com/drewnoakes/metadata-extractor) to access this field using `JpegDirectory`.

See this class: https://github.com/drewnoakes/metadata-extractor/blob/5773aa0e2877d5bafb091c6cbccb550ad2a58479/Source/com/drew/metadata/jpeg/JpegDirectory.java

I tried `TiffTag.IMAGE_WIDTH`, `TiffTag.IMAGE_LENGTH`, `ExifTag.EXIF_IMAGE_WIDTH` and `ExifTag.EXIF_IMAGE_HEIGHT` of `MetadataType.EXIF`, but these fields sometimes are `null`.

How to access these fields?

It's frame height and width of the SOF0 segment. It looks like that this is not made available as metadata.

**Comment by dragon66** [comment]
@StefanOltmann There is a specific metadata type "IMAGE" which I created to hold generic information for images like width and height but I may not have populated the values yet for this metadata. I remember I only put thumbnails into it by default. Will look into it when I get a chance.

**Comment by StefanOltmann** [comment]
I no longer need this.
